/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_CAN_PROXY_HPP_
#define V1_COMMONAPI_CAN_PROXY_HPP_

#include <v1/commonapi/CANProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class CANProxy
    : virtual public CAN,
      virtual public CANProxyBase,
      virtual public _AttributeExtensions... {
public:
    CANProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~CANProxy();

    typedef CAN InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute dis.
     */
    virtual DisAttribute& getDisAttribute() {
        return delegate_->getDisAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute rpm.
     */
    virtual RpmAttribute& getRpmAttribute() {
        return delegate_->getRpmAttribute();
    }



 private:
    std::shared_ptr< CANProxyBase> delegate_;
};

typedef CANProxy<> CANProxyDefault;

namespace CANExtensions {
    template <template <typename > class _ExtensionType>
    class DisAttributeExtension {
     public:
        typedef _ExtensionType< CANProxyBase::DisAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CANProxyBase::DisAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        DisAttributeExtension(CANProxyBase& proxy): attributeExtension_(proxy.getDisAttribute()) {
        }
    
        inline extension_type& getDisAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class RpmAttributeExtension {
     public:
        typedef _ExtensionType< CANProxyBase::RpmAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CANProxyBase::RpmAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        RpmAttributeExtension(CANProxyBase& proxy): attributeExtension_(proxy.getRpmAttribute()) {
        }
    
        inline extension_type& getRpmAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace CANExtensions

//
// CANProxy Implementation
//
template <typename ... _AttributeExtensions>
CANProxy<_AttributeExtensions...>::CANProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< CANProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< CANProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
CANProxy<_AttributeExtensions...>::~CANProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &CANProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool CANProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool CANProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& CANProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& CANProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> CANProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::commonapi::CANProxy,
    _AttributeExtension> {
    typedef typename ::v1::commonapi::CANProxy<
            ::v1::commonapi::CANExtensions::DisAttributeExtension<_AttributeExtension>, 
            ::v1::commonapi::CANExtensions::RpmAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_CAN_PROXY_HPP_
